require 'rake'
require 'rake/gempackagetask'

### begin gem task ###
# For generating a gem into: pkg/ just call
# $rake gem
# afterwards you can install it via 
# $sudo gem install pkg/<name>-<version>.gem
#
# further documentation at: http://www.rubygems.org/read/book/4
spec = Gem::Specification.new do |s|
  s.name 	 = "fipamessage"
  s.summary      = "Messages that fulfil the FIPA ACL standard"
  s.description  = File.read(File.join(File.dirname(__FILE__), 'README'))
  s.requirements = [ 'fipa_acl' ]
  s.version      = "0.1.0"
  s.author       = "Thomas Roehr"
  s.email        = "thomas.roehr@dfki.de"
  s.homepage     = "http://www.dfki.de/robotic"
  s.platform     = Gem::Platform::RUBY
  s.required_ruby_version = '>=1.8.7'
  s.files        = FileList['**/**/**'].exclude("pkg/*")
  s.executables  = ['']
  s.test_files   = Dir["test/test*.rb"]
  s.has_rdoc     = false
end

Rake::GemPackageTask.new(spec).define do |pkg|
	pkg.need_zip = true
	pkg.need_tar = true
end
### end gem task ###

### General setup task for local compilation
# since it is the default (see below) just call
# $rake 
#
RUBY = RbConfig::CONFIG['RUBY_INSTALL_NAME']

desc "build ruby FipaMessage extension"
namespace :setup do
	desc "builds FipaMessage C++ extension"
	task :ext do
		builddir = File.join('ext', 'build')
		prefix   = File.join(Dir.pwd, 'ext')
	
		FileUtils.mkdir_p builddir
		Dir.chdir(builddir) do
			if !system("#{RUBY} ../extconf.rb") || !system("make")
				throw "unable to build the extension"
			end
		end
		FileUtils.cp "ext/build/FipaMessage.so", "lib/fipa-message/"
	end
end

task :setup => [ "setup:ext" ]

desc "remove by-products of setup"
task :clean do
	FileUtils.rm_rf "pkg/"
	if File.exists?("ext/build")
		FileUtils.rm_rf("ext/build")
	end

	if File.exists?("lib/FipaMessage.so")
		FileUtils.rm "lib/FipaMessage.so"
	end
end

desc "build ruby package FipaMessage"
task :fipamessage => [ "setup" ] do 
end

#Set the default task for the Rakefile to be 'setup'
task :default => :fipamessage



  
